---
config:
  look: handDrawn
  theme: neutral
---
flowchart BT
 subgraph s5["Google BigQuery"]
        n51["Views"]
        n52["Tables"]
  end
 subgraph s6["Extract and transform"]
        n11["ETL scripts"]
        n17["dbt"]
  end
 subgraph s7["Data sources"]
        n61["DBs"]
        n62["APIs"]
        n63["Files"]
        n64["..."]
  end
    n5["Airflow"] -.-> n11 & n17 & s3["Power BI"] & n20["ML models"]
    n52 -- Data --> n20 & n51
    n51 -- Data --> s3
    n11 -- Table data --> n52
    n17 -- Models --> n51
    n20 -- Forecasts --> n52
    s7 -- Data --> n11
     n51:::Blueprint
     n52:::Blueprint
     n11:::Blueprint
     n17:::Blueprint
     n61:::Blueprint
     n62:::Blueprint
     n63:::Blueprint
     n64:::Blueprint
     n5:::Blueprint
     s3:::Blueprint
     n20:::Blueprint
     n20:::Blueprint
    classDef Blueprint stroke-width:2px, stroke-dasharray:none, stroke:#374D7C, fill:0754a6, color:#ffffff
    style s7 stroke:#0754a6
    style s6 stroke:#0754a6
    style s5 stroke:#0754a6
    linkStyle 0 stroke:#0754a6,fill:none
    linkStyle 1 stroke:#0754a6,fill:none
    linkStyle 2 stroke:#0754a6,fill:none
    linkStyle 3 stroke:#0754a6,fill:none
    linkStyle 4 stroke:#0754a6,fill:none
    linkStyle 5 stroke:#0754a6,fill:none
    linkStyle 6 stroke:#0754a6,fill:none
    linkStyle 7 stroke:#0754a6
    linkStyle 8 stroke:#0754a6,fill:none
    linkStyle 9 stroke:#0754a6,fill:none
    linkStyle 10 stroke:#0754a6,fill:none
