---
config:
  look: handDrawn
  theme: neutral
---
flowchart BT
 subgraph s3["Datasets"]
        n22["Sales"]
        n23["Supply"]
        n24["Finance"]
        n25["HR"]
  end
 subgraph s4["Reports and dashboards"]
        n26["Report 2"]
        n27["Report 3"]
        n29["Report 1"]
        n40["Dashboard 1"]
        n42["..."]
        n41["Report n"]
  end
 subgraph s5["Google BigQuery"]
        n51["Views"]
  end
    n51 --> n24 & n22 & n25 & n23
    n22 --> n26 & n40
    n23 --> n27 & n40 & n41
    n24 --> n29
    n25 --> n40
     n22:::Blueprint
     n23:::Blueprint
     n24:::Blueprint
     n25:::Blueprint
     n26:::Blueprint
     n27:::Blueprint
     n29:::Blueprint
     n40:::Blueprint
     n42:::Blueprint
     n41:::Blueprint
     n51:::Blueprint
    classDef Blueprint stroke-width:2px, stroke-dasharray:none, stroke:#374D7C, fill:0754a6, color:#ffffff
    style s3 stroke:#0754a6,color:#0754a6
    style s5 stroke:#0754a6,color:#0754a6
    style s4 stroke:#0754a6,color:#0754a6
    linkStyle 0 stroke:#0754a6,fill:none
    linkStyle 1 stroke:#0754a6,fill:none
    linkStyle 2 stroke:#0754a6,fill:none
    linkStyle 3 stroke:#0754a6,fill:none
    linkStyle 4 stroke:#0754a6,fill:none
    linkStyle 5 stroke:#0754a6,fill:none
    linkStyle 6 stroke:#0754a6,fill:none
    linkStyle 7 stroke:#0754a6,fill:none
    linkStyle 8 stroke:#0754a6,fill:none
    linkStyle 9 stroke:#0754a6,fill:none
    linkStyle 10 stroke:#0754a6,fill:none
